

#undef AUTHORIZATION

// AUTHORIZATION MACRO // ------------------------------------------------------
#undef BOOSTER_MACRO_API_CONTROLLER_AUTHORIZATION_1
#undef BOOSTER_MACRO_API_CONTROLLER_AUTHORIZATION_2
#undef BOOSTER_MACRO_API_CONTROLLER_AUTHORIZATION

// __INFO
#undef BOOSTER_MACRO_API_CONTROLLER_AUTHORIZATION_INFO_1
#undef BOOSTER_MACRO_API_CONTROLLER_AUTHORIZATION_INFO_2
#undef BOOSTER_MACRO_API_CONTROLLER_AUTHORIZATION_INFO
