

#undef BOOSTER_MACRO_API_CONTROLLER_PARAM_MACRO
#undef BOOSTER_MACRO_API_CONTROLLER_PARAM_INFO
#undef BOOSTER_MACRO_API_CONTROLLER_PARAM_TYPE
#undef BOOSTER_MACRO_API_CONTROLLER_PARAM_NAME
#undef BOOSTER_MACRO_API_CONTROLLER_PARAM_TYPE_STR
#undef BOOSTER_MACRO_API_CONTROLLER_PARAM_NAME_STR
#undef BOOSTER_MACRO_API_CONTROLLER_PARAM

#undef REQUEST
#undef HEADER
#undef PATH
#undef QUERIES
#undef QUERY
#undef BODY_STRING
#undef BODY_DTO

// INIT // ------------------------------------------------------

#undef REST_CONTROLLER_INIT

#undef BOOSTER_MACRO_API_CONTROLLER_MACRO_SELECTOR

// REQUEST MACRO // ------------------------------------------------------

#undef BOOSTER_MACRO_API_CONTROLLER_REQUEST
#undef BOOSTER_MACRO_API_CONTROLLER_REQUEST_INFO

// HEADER MACRO // ------------------------------------------------------

#undef BOOSTER_MACRO_API_CONTROLLER_HEADER_1
#undef BOOSTER_MACRO_API_CONTROLLER_HEADER_2
#undef BOOSTER_MACRO_API_CONTROLLER_HEADER

// __INFO

#undef BOOSTER_MACRO_API_CONTROLLER_HEADER_INFO_1
#undef BOOSTER_MACRO_API_CONTROLLER_HEADER_INFO_2
#undef BOOSTER_MACRO_API_CONTROLLER_HEADER_INFO

// PATH MACRO // ------------------------------------------------------

#undef BOOSTER_MACRO_API_CONTROLLER_PATH_1
#undef BOOSTER_MACRO_API_CONTROLLER_PATH_2
#undef BOOSTER_MACRO_API_CONTROLLER_PATH

// __INFO

#undef BOOSTER_MACRO_API_CONTROLLER_PATH_INFO_1
#undef BOOSTER_MACRO_API_CONTROLLER_PATH_INFO_2
#undef BOOSTER_MACRO_API_CONTROLLER_PATH_INFO

// QUERIES MACRO // ------------------------------------------------------

#undef BOOSTER_MACRO_API_CONTROLLER_QUERIES
#undef BOOSTER_MACRO_API_CONTROLLER_QUERIES_INFO

// QUERY MACRO // ------------------------------------------------------

#undef BOOSTER_MACRO_API_CONTROLLER_QUERY_1
#undef BOOSTER_MACRO_API_CONTROLLER_QUERY_2
#undef BOOSTER_MACRO_API_CONTROLLER_QUERY

// __INFO

#undef BOOSTER_MACRO_API_CONTROLLER_QUERY_INFO_1
#undef BOOSTER_MACRO_API_CONTROLLER_QUERY_INFO_2
#undef BOOSTER_MACRO_API_CONTROLLER_QUERY_INFO

// BODY_STRING MACRO // ------------------------------------------------------

#undef BOOSTER_MACRO_API_CONTROLLER_BODY_STRING

// __INFO

#undef BOOSTER_MACRO_API_CONTROLLER_BODY_STRING_INFO

// BODY_DTO MACRO // ------------------------------------------------------

#undef BOOSTER_MACRO_API_CONTROLLER_BODY_DTO

// __INFO

#undef BOOSTER_MACRO_API_CONTROLLER_BODY_DTO_INFO

// FOR EACH // ------------------------------------------------------

#undef BOOSTER_MACRO_API_CONTROLLER_FOR_EACH_PARAM_DECL
#undef BOOSTER_MACRO_API_CONTROLLER_FOR_EACH_PARAM_PUT
#undef BOOSTER_MACRO_API_CONTROLLER_FOR_EACH_PARAM_CALL
#undef BOOSTER_MACRO_API_CONTROLLER_FOR_EACH_PARAM_INFO

// ENDPOINT_INFO MACRO // ------------------------------------------------------

#undef ENDPOINT_INFO

// ENDPOINT MACRO // ------------------------------------------------------

#undef BOOSTER_MACRO_API_CONTROLLER_ENDPOINT_DECL_DEFAULTS

#undef BOOSTER_MACRO_API_CONTROLLER_ENDPOINT_DECL_0
#undef BOOSTER_MACRO_API_CONTROLLER_ENDPOINT_0

#undef BOOSTER_MACRO_API_CONTROLLER_ENDPOINT_DECL_1
#undef BOOSTER_MACRO_API_CONTROLLER_ENDPOINT_1

#undef BOOSTER_MACRO_API_CONTROLLER_ENDPOINT_MACRO_0
#undef BOOSTER_MACRO_API_CONTROLLER_ENDPOINT_MACRO_1

#undef ENDPOINT

#undef ENDPOINT_INTERCEPTOR

// ENDPOINT ASYNC MACRO // ------------------------------------------------------

#undef BOOSTER_MACRO_API_CONTROLLER_ENDPOINT_ASYNC_DECL_DEFAULTS
#undef BOOSTER_MACRO_API_CONTROLLER_ENDPOINT_ASYNC_DECL
#undef ENDPOINT_ASYNC
#undef ENDPOINT_ASYNC_INIT

#undef ENDPOINT_INTERCEPTOR_ASYNC
