

#define BUNDLE(TYPE, ...) \
BOOSTER_MACRO_API_CONTROLLER_PARAM(BOOSTER_MACRO_API_CONTROLLER_BUNDLE, BOOSTER_MACRO_API_CONTROLLER_BUNDLE_INFO, TYPE, (__VA_ARGS__))

// BUNDLE MACRO // ------------------------------------------------------

#define BOOSTER_MACRO_API_CONTROLLER_BUNDLE_1(TYPE, NAME) \
TYPE NAME = __request->getBundleData<TYPE>(#NAME);

#define BOOSTER_MACRO_API_CONTROLLER_BUNDLE_2(TYPE, NAME, QUALIFIER) \
TYPE NAME = __request->getBundleData<TYPE>(QUALIFIER);

#define BOOSTER_MACRO_API_CONTROLLER_BUNDLE(TYPE, PARAM_LIST) \
BOOSTER_MACRO_API_CONTROLLER_MACRO_SELECTOR(BOOSTER_MACRO_API_CONTROLLER_BUNDLE_, TYPE, BOOSTER_MACRO_UNFOLD_VA_ARGS PARAM_LIST)

#define BOOSTER_MACRO_API_CONTROLLER_BUNDLE_INFO(TYPE, PARAM_LIST)
