



#undef BOOSTER_MACRO_API_CLIENT_PARAM_MACRO
#undef BOOSTER_MACRO_API_CLIENT_PARAM_TYPE
#undef BOOSTER_MACRO_API_CLIENT_PARAM_NAME
#undef BOOSTER_MACRO_API_CLIENT_PARAM_TYPE_STR
#undef BOOSTER_MACRO_API_CLIENT_PARAM_NAME_STR
#undef BOOSTER_MACRO_API_CLIENT_PARAM

#undef HEADER
#undef PATH
#undef QUERY
#undef BODY
#undef BODY_DTO
#undef BODY_STRING
#undef AUTHORIZATION
#undef AUTHORIZATION_BASIC
//

#undef BOOSTER_MACRO_API_CLIENT_MACRO_SELECTOR

// INIT

#undef API_CLIENT_INIT

// HEADER MACRO

#undef BOOSTER_MACRO_API_CLIENT_HEADER_1
#undef BOOSTER_MACRO_API_CLIENT_HEADER_2

#undef BOOSTER_MACRO_API_CLIENT_HEADER

// PATH MACRO

#undef BOOSTER_MACRO_API_CLIENT_PATH_1
#undef BOOSTER_MACRO_API_CLIENT_PATH_2

#undef BOOSTER_MACRO_API_CLIENT_PATH

// QUERY MACRO

#undef BOOSTER_MACRO_API_CLIENT_QUERY_1
#undef BOOSTER_MACRO_API_CLIENT_QUERY_2

#undef BOOSTER_MACRO_API_CLIENT_QUERY

// BODY MACRO

#undef BOOSTER_MACRO_API_CLIENT_BODY

// BODY_DTO MACRO

#undef BOOSTER_MACRO_API_CLIENT_BODY_DTO

// BODY_STRING MACRO

#undef BOOSTER_MACRO_API_CLIENT_BODY_STRING

// AUTHORIZATION MACRO

#undef BOOSTER_MACRO_API_CLIENT_AUTHORIZATION_2

#undef BOOSTER_MACRO_API_CLIENT_AUTHORIZATION

// AUTHORIZATION_BASIC MACRO

#undef BOOSTER_MACRO_API_CLIENT_AUTHORIZATION_BASIC_1

#undef BOOSTER_MACRO_API_CLIENT_AUTHORIZATION_BASIC

// FOR EACH

#undef BOOSTER_MACRO_API_CLIENT_PARAM_DECL
#undef BOOSTER_MACRO_API_CLIENT_PARAM_PUT

// API_CALL MACRO

#undef BOOSTER_API_CALL_0
#undef BOOSTER_API_CALL_1

#undef BOOSTER_API_CALL_MACRO_0
#undef BOOSTER_API_CALL_MACRO_1

#undef API_CALL

// API_CALL_ASYNC MACRO

#undef BOOSTER_API_CALL_ASYNC_0
#undef BOOSTER_API_CALL_ASYNC_1

#undef BOOSTER_API_CALL_ASYNC_MACRO_0
#undef BOOSTER_API_CALL_ASYNC_MACRO_1

#undef API_CALL_ASYNC

#undef API_CALL_HEADERS
