


#undef BOOSTER_MACRO_DB_CLIENT_PARAM_TYPE
#undef BOOSTER_MACRO_DB_CLIENT_PARAM_NAME
#undef BOOSTER_MACRO_DB_CLIENT_PARAM_TYPE_STR
#undef BOOSTER_MACRO_DB_CLIENT_PARAM_NAME_STR

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_MACRO
#undef BOOSTER_MACRO_DB_CLIENT_PREPARE_MACRO

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_MACRO_TYPE

#undef BOOSTER_MACRO_DB_CLIENT_PARAM
#undef BOOSTER_MACRO_DB_CLIENT_PREPARE

#undef PARAM
#undef PREPARE

//////////////////////////////////////////////////////////////////////////

#undef BOOSTER_MACRO_DB_CLIENT_MACRO_SELECTOR

//////////////////////////////////////////////////////////////////////////

// PARAM MACRO USE-CASE

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PARAM_PUT_DECL

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PARAM_PUT_TYPE

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PARAM_PUT_BODY

// PARAM MACRO

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PARAM_1

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PARAM_2

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PARAM

// PARAM_TYPE MACRO

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PARAM_TYPE_1

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PARAM_TYPE_2

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PARAM_TYPE

// PREPARE MACRO USE-CASE

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PREPARE_PUT_DECL

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PREPARE_PUT_TYPE

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PREPARE_PUT_BODY

// PREPARE MACRO

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PREPARE

// PARAMS USE-CASE

#undef BOOSTER_MACRO_PARAM_USECASE_DECL
#undef BOOSTER_MACRO_PARAM_USECASE_TYPE
#undef BOOSTER_MACRO_PARAM_USECASE_BODY

// FOR EACH

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PUT_DECL

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PUT_TYPE

#undef BOOSTER_MACRO_DB_CLIENT_PARAM_PUT

// QUERY MACRO

#undef BOOSTER_QUERY_0


#undef BOOSTER_QUERY_1

// Chooser

#undef BOOSTER_QUERY_MACRO_0

#undef BOOSTER_QUERY_MACRO_1

#undef QUERY
